understand_cv documentation spelling updates
rodrigo-arenas/Sklearn-genetic-opt pull request #57
Opened 2021-06-30 18:21 UTC by Turtle24

I updated the understand_cv documents grammar and spelling a bit. This is for #43 and I'll slowly go over all the documentation because I want to better understand the package and work on the inner workings eventually.

2021-06-30 20:19 UTC, rodrigo-arenas requested changes
Ey thanks! This is really useful, I see a lot of typos I missed and a better redaction.

I just have a comment on the change from "and search problems" to "and search of problems" in the line 25. I think it should remain the same.

What I want to tell, is that there is a subset of problems in optimization, that are called "search problems", see for example [this page](https://en.wikipedia.org/wiki/Local_search_(optimization))

Let me know what you think, and if you are agree, let's change that line before merging, thanks!

2021-07-01 06:19 UTC, Turtle24 commented
> 
> 
> Ey thanks! This is really useful, I see a lot of typos I missed and a better redaction.
> 
> I just have a comment on the change from "and search problems" to "and search of problems" in the line 25. I think it should remain the same.
> 
> What I want to tell, is that there is a subset of problems in optimization, that are called "search problems", see for example [this page](https://en.wikipedia.org/wiki/Local_search_(optimization))
> 
> Let me know what you think, and if you are agree, let's change that line before merging, thanks!

Ok awesome, I updated it. Yeah you're right, I missed the context so I get what you're saying 👍🏽

2021-07-01 14:51 UTC, rodrigo-arenas approved these changes

2021-07-01 14:51 UTC, rodrigo-arenas commented
Great, this is looking good! 
Thanks again

2021-07-01 14:52 UTC, merged